### ISSUE TITLE
Supporting `strict = False` when loading model 

### ISSUE THREAD

**Issue by XingruiWang** [vacancy/Jacinle#16]
Hi,

When loading the model checkpoint in function `TrainerEnv.load_checkpoint()`, is there a way to support the parameter `strict=False` to ignore non-matching keys loading, similar to the `load_state_dict()` method in original pytorch?

**Comment by vacancy** [comment]
Should work in the latest version: 737be2135f10b2b966917495692e3d1f7ddb5c1d

**Comment by XingruiWang** [comment]
Thanks!
