### ISSUE TITLE
Import _mask error

### ISSUE THREAD

**Issue by iLegolas** [vacancy/Jacinle#4]
```
  File "/home/stark/Desktop/Minor-project-2/Jacinle/jaclearn/vision/coco/pycocotools/mask.py", line 3, in <module>
    from . import _mask as _mask
ImportError: cannot import name '_mask'
```
Please someone help me.

**Comment by zhmd** [comment]
`pip install pycocotools`

works for me

**Comment by tardis-forever** [comment]
I tried to install `pycocotools` via `conda install -c conda-forge pycocotools` as conda is suggested in the readme, but it didn't work, I'm still getting this error

**Comment by tardis-forever** [comment]
run `python3 setup.py build_ext --inplace` in `Jacinle/jaclearn/vision/coco`, it helped me
